/// <reference types="jquery" />
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var GraffitiExtension;
(function (GraffitiExtension) {
    class ImageRetreiver {
        constructor() {
            this.unsplashSearchQuery = "lgbt";
        }
        getRandomImage(containerHeight = 100, containerWidth = 300) {
            return this.getUnsplashHotlinkDetails(containerHeight, containerWidth);
        }
        getUnsplashHotlinkDetails(height, width) {
            return __awaiter(this, void 0, void 0, function* () {
                var orientation = width > height ? "landscape" : "portrait";
                var response = yield jQuery.get({
                    url: `https://api.unsplash.com/photos/random?query=${this.unsplashSearchQuery}&orientation=${orientation}`,
                    headers: {
                        "Authorization": `Client-ID ${GRAFFITI_EXT_UNSPLASH_CLIENT_ID}`
                    }
                });
                return {
                    url: response.urls.custom || response.urls.regular,
                    aspectRatio: response.width / response.height,
                    description: response.description,
                    primaryColor: response.color
                };
            });
        }
    }
    GraffitiExtension.ImageRetreiver = ImageRetreiver;
})(GraffitiExtension || (GraffitiExtension = {}));
var GraffitiExtension;
(function (GraffitiExtension) {
    GraffitiExtension.matchPhrases = [
        "good friends",
        "uncivilised",
        "gypo",
        "gypos",
        "cunt",
        "cunts",
        "peckerwood",
        "peckerwoods",
        "raghead",
        "ragheads",
        "cripple",
        "cripples",
        "niggur",
        "niggurs",
        "yellow bone",
        "yellow bones",
        "muzzie",
        "muzzies",
        "niggar",
        "niggars",
        "nigger",
        "niggers",
        "greaseball",
        "greaseballs",
        "white trash",
        "white trashes",
        "nig nog",
        "nig nogs",
        "faggot",
        "faggots",
        "cotton picker",
        "cotton pickers",
        "darkie",
        "darkies",
        "hoser",
        "hosers",
        "Uncle Tom",
        "Uncle Toms",
        "Jihadi",
        "Jihadis",
        "retard",
        "retards",
        "hillbilly",
        "hillbillies",
        "fag",
        "fags",
        "trailer trash",
        "trailer trashes",
        "pikey",
        "pikies",
        "nicca",
        "niccas",
        "tranny",
        "trannies",
        "porch monkey",
        "porch monkies",
        "wigger",
        "wiggers",
        "wetback",
        "wetbacks",
        "nigglet",
        "nigglets",
        "wigga",
        "wiggas",
        "dhimmi",
        "dhimmis",
        "honkey",
        "honkies",
        "eurotrash",
        "eurotrashes",
        "yardie",
        "yardies",
        "trailer park trash",
        "trailer park trashes",
        "niggah",
        "niggahes",
        "yokel",
        "yokels",
        "nigguh",
        "nigguhes",
        "camel jockey",
        "camel jockies",
        "honkie",
        "honkies",
        "niglet",
        "niglets",
        "gyppo",
        "gyppos",
        "dyke",
        "dykes",
        "half breed",
        "honky",
        "honkies",
        "race traitor",
        "race traitors",
        "jiggaboo",
        "jiggaboos",
        "Chinaman",
        "Chinamans",
        "curry muncher",
        "curry munchers",
        "jungle bunny",
        "jungle bunnies",
        "coon ass",
        "coon asses",
        "newfie",
        "newfies",
        "house nigger",
        "house niggers",
        "limey",
        "limies",
        "red bone",
        "red bones",
        "guala",
        "gualas",
        "plastic paddy",
        "plastic paddies",
        "whigger",
        "whiggers",
        "jigaboo",
        "jigaboos",
        "nig",
        "nigs",
        "Zionazi",
        "Zionazis",
        "spear chucker",
        "spear chuckers",
        "niggress",
        "niggresses",
        "yobbo",
        "yobbos",
        "border jumper",
        "border jumpers",
        "sperg",
        "spergs",
        "pommy",
        "pommies",
        "munter",
        "munters",
        "tar baby",
        "tar babies",
        "pommie",
        "pommies",
        "gyp",
        "gyps",
        "anchor baby",
        "anchor babies",
        "twat",
        "twats",
        "border hopper",
        "border hoppers",
        "queer",
        "queers",
        "darky",
        "darkies",
        "ching chong",
        "ching chongs",
        "khazar",
        "khazars",
        "gippo",
        "gippos",
        "skanger",
        "skangers",
        "beaner",
        "beaners",
        "quadroon",
        "quadroons",
        "gator bait",
        "gator baits",
        "Cushite",
        "Cushites",
        "mud shark",
        "mud sharks",
        "cracker",
        "crackers",
        "dune coon",
        "dune coons",
        "pickaninny",
        "pickaninnies",
        "slant eye",
        "slant eyes",
        "sideways vagina",
        "sideways vaginas",
        "hick",
        "hicks",
        "camel fucker",
        "camel fuckers",
        "redneck",
        "rednecks",
        "spiv",
        "spivs",
        "zipperhead",
        "zipperheads",
        "Kushite",
        "Kushites",
        "Shylock",
        "Shylocks",
        "gook",
        "gooks",
        "papist",
        "papists",
        "hymie",
        "hymies",
        "wog",
        "wogs",
        "scally",
        "scallies",
        "coon",
        "coons",
        "whitey",
        "whities",
        "nigette",
        "nigettes",
        "paki",
        "pakis",
        "towel head",
        "towel heads",
        "Argie",
        "Argies",
        "wexican",
        "wexicans",
        "jigger",
        "jiggers",
        "injun",
        "injuns",
        "ocker",
        "ockers",
        "polack",
        "polacks",
        "moulie",
        "moulies",
        "niggor",
        "niggors",
        "scanger",
        "scangers",
        "ofay",
        "ofaies",
        "jigga",
        "jiggas",
        "redskin",
        "redskins",
        "chonky",
        "chonkies",
        "hebro",
        "hebros",
        "wop",
        "wops",
        "chink",
        "chinks",
        "sideways pussy",
        "sideways pussies",
        "paleface",
        "palefaces",
        "wagon burner",
        "wagon burners",
        "nigra",
        "nigras",
        "spic",
        "spics",
        "spics",
        "jocky",
        "jockies",
        "kraut",
        "krauts",
        "steek",
        "steeks",
        "coolie",
        "coolies",
        "gooky",
        "gookies",
        "octaroon",
        "octaroons",
        "bint",
        "bints",
        "shit heel",
        "shit heels",
        "squaw",
        "squaws",
        "bog trotter",
        "bog trotters",
        "Oriental",
        "Orientals",
        "halfrican",
        "halfricans",
        "paddy",
        "paddies",
        "groid",
        "groids",
        "jiggabo",
        "jiggabos",
        "jigg",
        "jiggs",
        "jant",
        "jants",
        "spide",
        "spides",
        "camel humper",
        "camel humpers",
        "white nigger",
        "white niggers",
        "ZOG",
        "ZOGs",
        "diaper head",
        "diaper heads",
        "heeb",
        "heebs",
        "Christ killer",
        "Christ killers",
        "piker",
        "pikers",
        "higger",
        "higgers",
        "lemonhead",
        "lemonheads",
        "Hun",
        "Huns",
        "popolo",
        "popolos",
        "cowboy killer",
        "cowboy killers",
        "jhant",
        "jhants",
        "eyetie",
        "eyeties",
        "mockey",
        "mockies",
        "alligator bait",
        "alligator baits",
        "Jap",
        "Japs",
        "shanty Irish",
        "shanty Irishes",
        "redlegs",
        "mulignan",
        "mulignans",
        "jockie",
        "jockies",
        "mangia cake",
        "mangia cakes",
        "moulinyan",
        "moulinyans",
        "nigar",
        "nigars",
        "darkey",
        "darkies",
        "gurrier",
        "gurriers",
        "lubra",
        "lubras",
        "Buckwheat",
        "Buckwheats",
        "mulato",
        "mulatos",
        "prairie nigger",
        "prairie niggers",
        "kyke",
        "kykes",
        "boonie",
        "boonies",
        "mick",
        "micks",
        "bluegum",
        "bluegums",
        "spigger",
        "spiggers",
        "border bunny",
        "border bunnies",
        "kike",
        "kikes",
        "moulignon",
        "moulignons",
        "roundeye",
        "roundeyes",
        "ginzo",
        "ginzos",
        "Jewbacca",
        "Jewbaccas",
        "booner",
        "booners",
        "nigre",
        "nigres",
        "scallie",
        "scallies",
        "niger",
        "nigers",
        "dinge",
        "dinges",
        "Leb",
        "Lebs",
        "Lebbo",
        "Lebbos",
        "sambo",
        "sambos",
        "Africoon",
        "Africoons",
        "ling ling",
        "ling lings",
        "gub",
        "gubs",
        "banana bender",
        "banana benders",
        "japie",
        "japies",
        "island nigger",
        "island niggers",
        "hairyback",
        "hairybacks",
        "lugan",
        "lugans",
        "Bog Irish",
        "Bog Irishes",
        "blaxican",
        "blaxicans",
        "moke",
        "mokes",
        "nigor",
        "nigors",
        "bix nood",
        "bix noods",
        "Kushi",
        "Kushis",
        "guala guala",
        "guala gualas",
        "hoosier",
        "hoosiers",
        "thicklips",
        "mook",
        "mooks",
        "muk",
        "muks",
        "soup taker",
        "soup takers",
        "senga",
        "sengas",
        "Cushi",
        "Cushis",
        "pogue",
        "pogues",
        "abo",
        "abos",
        "ping pang",
        "ping pangs",
        "proddy dog",
        "proddy dogs",
        "boong",
        "boongs",
        "dago",
        "dagos",
        "dogun",
        "doguns",
        "mocky",
        "mockies",
        "poppadom",
        "poppadoms",
        "Gwat",
        "Gwats",
        "ice nigger",
        "ice niggers",
        "spook",
        "spooks",
        "Afro-Saxon",
        "Afro-Saxons",
        "guido",
        "guidos",
        "latrino",
        "latrinos",
        "lowlander",
        "lowlanders",
        "mockie",
        "mockies",
        "moky",
        "mokies",
        "mosshead",
        "mossheads",
        "African catfish",
        "African catfishes",
        "gyppy",
        "gyppies",
        "timber nigger",
        "timber niggers",
        "Americoon",
        "Americoons",
        "camel cowboy",
        "camel cowboies",
        "eh hole",
        "eh holes",
        "Hunyak",
        "Hunyaks",
        "slopehead",
        "slopeheads",
        "teabagger",
        "teabaggers",
        "Armo",
        "Armos",
        "bitch",
        "bitches",
        "greaser",
        "greasers",
        "Honyock",
        "Honyocks",
        "mud person",
        "mud persons",
        "pineapple nigger",
        "pineapple niggers",
        "retarded",
        "semihole",
        "semiholes",
        "Amo",
        "Amos",
        "border nigger",
        "border niggers",
        "buckra",
        "buckras",
        "burrhead",
        "burrheads",
        "cab nigger",
        "cab niggers",
        "carpet pilot",
        "carpet pilots",
        "pancake face",
        "pancake faces",
        "spigotty",
        "spigotties",
        "carrot snapper",
        "carrot snappers",
        "chili shitter",
        "chili shitters",
        "curry slurper",
        "curry slurpers",
        "ghetto hamster",
        "ghetto hamsters",
        "ice monkey",
        "ice monkies",
        "roofucker",
        "roofuckers",
        "Velcro head",
        "Velcro heads",
        "wiggerette",
        "wiggerettes",
        "beach nigger",
        "beach niggers",
        "bean dipper",
        "bean dippers",
        "bog hopper",
        "bog hoppers",
        "Buddhahead",
        "Buddhaheads",
        "camel jacker",
        "camel jackers",
        "Caublasian",
        "Caublasians",
        "cave nigger",
        "cave niggers",
        "cow kisser",
        "cow kissers",
        "dune nigger",
        "dune niggers",
        "four by two",
        "four by twos",
        "fresh off the boat",
        "fresh off the boats",
        "gin jockey",
        "gin jockies",
        "golliwog",
        "golliwogs",
        "guinea",
        "guineas",
        "Jim Fish",
        "Jim Fishes",
        "mackerel snapper",
        "mackerel snappers",
        "octroon",
        "octroons",
        "pohm",
        "pohms",
        "pussy",
        "pussies",
        "Russellite",
        "Russellites",
        "spice nigger",
        "spice niggers",
        "uncivilized",
        "Whipped",
        "albino",
        "albinos",
        "ape",
        "apes",
        "Aunt Jemima",
        "Aunt Jemimas",
        "buckethead",
        "bucketheads",
        "Chinese wetback",
        "Chinese wetbacks",
        "chug",
        "chugs",
        "curry stinker",
        "curry stinkers",
        "dyke jumper",
        "dyke jumpers",
        "eight ball",
        "eight balls",
        "gun burglar",
        "gun burglars",
        "ikey mo",
        "ikey mos",
        "lawn jockey",
        "lawn jockies",
        "leprechaun",
        "leprechauns",
        "mutt",
        "mutts",
        "negro",
        "negros",
        "negroes",
        "nitchee",
        "nitchees",
        "sooty",
        "sooties",
        "spick",
        "spicks",
        "tinkard",
        "tinkards",
        "uncircumcised baboon",
        "uncircumcised baboons",
        "zigabo",
        "zigabos",
        "abbo",
        "abbos",
        "Anglo",
        "Anglos",
        "Aunt Jane",
        "Aunt Janes",
        "Aunt Mary",
        "Aunt Maries",
        "Aunt Sally",
        "Aunt Sallies",
        "azn",
        "azns",
        "bamboo coon",
        "bamboo coons",
        "banana lander",
        "banana landers",
        "banjo lips",
        "bans and cans",
        "beaner shnitzel",
        "beaner shnitzels",
        "beaney",
        "beanies",
        "Bengali",
        "Bengalis",
        "bhrempti",
        "bhremptis",
        "bird",
        "birds",
        "bitter clinger",
        "bitter clingers",
        "black Barbie",
        "black Barbies",
        "black dago",
        "black dagos",
        "blockhead",
        "blockheads",
        "bog jumper",
        "bog jumpers",
        "boon",
        "boons",
        "boonga",
        "boongas",
        "Bounty bar",
        "Bounty bars",
        "boxhead",
        "boxheads",
        "brass ankle",
        "brass ankles",
        "brownie",
        "brownies",
        "buffie",
        "buffies",
        "bug eater",
        "bug eaters",
        "buk buk",
        "buk buks",
        "bumblebee",
        "bumblebees",
        "bung",
        "bungs",
        "bunga",
        "bungas",
        "butterhead",
        "butterheads",
        "can eater",
        "can eaters",
        "celestial",
        "celestials",
        "Charlie",
        "Charlies",
        "chee chee",
        "chee chees",
        "chi chi",
        "chi chis",
        "chigger",
        "chiggers",
        "chinig",
        "chinigs",
        "chink a billy",
        "chink a billies",
        "chunky",
        "chunkies",
        "clam",
        "clams",
        "clamhead",
        "clamheads",
        "colored",
        "coloured",
        "crow",
        "crows",
        "dego",
        "degos",
        "dink",
        "dinks",
        "dogan",
        "dogans",
        "domes",
        "dot head",
        "dot heads",
        "eggplant",
        "eggplants",
        "Fairy",
        "Fairies",
        "fez",
        "fezs",
        "FOB",
        "FOBs",
        "fog nigger",
        "fog niggers",
        "fuzzy",
        "fuzzies",
        "fuzzy wuzzy",
        "fuzzy wuzzies",
        "gable",
        "gables",
        "Gerudo",
        "Gerudos",
        "gew",
        "gews",
        "ghetto",
        "ghettos",
        "gipp",
        "gipps",
        "gook eye",
        "gook eyes",
        "gyppie",
        "gyppies",
        "heinie",
        "heinies",
        "ho",
        "hos",
        "hoe",
        "hoes",
        "Honyak",
        "Honyaks",
        "Hunkie",
        "Hunkies",
        "Hunky",
        "Hunkies",
        "Hunyock",
        "Hunyocks",
        "ike",
        "ikes",
        "ikey",
        "ikies",
        "iky",
        "ikies",
        "jig",
        "jigs",
        "jigarooni",
        "jigaroonis",
        "jijjiboo",
        "jijjiboos",
        "kotiya",
        "kotiyas",
        "mickey",
        "mickies",
        "moch",
        "moches",
        "mock",
        "mocks",
        "mong",
        "mongs",
        "monkey",
        "monkies",
        "Moor",
        "Moors",
        "moss eater",
        "moss eaters",
        "moxy",
        "moxies",
        "muktuk",
        "muktuks",
        "mung",
        "mungs",
        "munt",
        "munts",
        "ned",
        "net head",
        "net heads",
        "nichi",
        "nichis",
        "nichiwa",
        "nichiwas",
        "nidge",
        "nidges",
        "nip",
        "nips",
        "nitchie",
        "nitchies",
        "nitchy",
        "nitchies",
        "Orangie",
        "Orangies",
        "Oreo",
        "Oreos",
        "papoose",
        "papooses",
        "piky",
        "pikies",
        "pinto",
        "pintos",
        "pointy head",
        "pointy heads",
        "pollo",
        "pollos",
        "pom",
        "poms",
        "pommie grant",
        "pommie grants",
        "Punjab",
        "Punjabs",
        "rube",
        "rubes",
        "sawney",
        "sawnies",
        "scag",
        "scags",
        "seppo",
        "seppos",
        "septic",
        "septics",
        "shant",
        "shants",
        "sheeny",
        "sheenies",
        "sheepfucker",
        "sheepfuckers",
        "Shelta",
        "Sheltas",
        "shiner",
        "shiners",
        "shit kicker",
        "shit kickers",
        "Shy",
        "Shies",
        "sideways cooter",
        "sideways cooters",
        "skag",
        "skags",
        "Skippy",
        "Skippies",
        "slag",
        "slags",
        "slant",
        "slants",
        "slit",
        "slits",
        "slope",
        "slopes",
        "slopey",
        "slopies",
        "slopy",
        "slopies",
        "smoke jumper",
        "smoke jumpers",
        "smoked Irish",
        "smoked Irishes",
        "smoked Irishman",
        "smoked Irishmans",
        "sole",
        "soles",
        "spickaboo",
        "spickaboos",
        "spig",
        "spigs",
        "spik",
        "spiks",
        "spink",
        "spinks",
        "squarehead",
        "squareheads",
        "squinty",
        "squinties",
        "stovepipe",
        "stovepipes",
        "sub human",
        "sub humans",
        "sucker fish",
        "sucker fishes",
        "Taffy",
        "Taffies",
        "teapot",
        "teapots",
        "tenker",
        "tenkers",
        "tincker",
        "tinckers",
        "tinkar",
        "tinkars",
        "tinker",
        "tinkers",
        "tinkere",
        "tinkeres",
        "trash",
        "trashes",
        "tree jumper",
        "tree jumpers",
        "tunnel digger",
        "tunnel diggers",
        "Twinkie",
        "Twinkies",
        "tyncar",
        "tyncars",
        "tynekere",
        "tynekeres",
        "tynkard",
        "tynkards",
        "tynkare",
        "tynkares",
        "tynker",
        "tynkers",
        "tynkere",
        "tynkeres",
        "WASP",
        "WASPs",
        "Yank",
        "Yanks",
        "Yankee",
        "Yankees",
        "yellow",
        "yellows",
        "yid",
        "yids",
        "yob",
        "yobs",
        "zebra",
        "zebras",
        "zippohead",
        "zippoheads",
        "ZOG lover",
        "ZOG lovers’",
        "knacker",
        "knackers",
        "shyster",
        "shysters",
        "bogan",
        "bogans",
        "hayseed",
        "moon cricket",
        "moon crickets",
        "mud duck",
        "mud ducks",
        "surrender monkey",
        "surrender monkies",
        "bludger",
        "bludgers",
        "charver",
        "charvers",
        "dole bludger",
        "dole bludgers",
        "chav",
        "chavs",
        "sheister",
        "sheisters",
        "charva",
        "charvas",
        "touch of the tar brush",
        "touch of the tar brushes",
        "Northern monkey",
        "Northern monkies",
        "Southern fairy",
        "Southern fairies",
        "gubba",
        "gubbas",
        "stump jumper",
        "stump jumpers",
        "hebe",
        "hebes",
        "millie",
        "millies",
        "quashie",
        "quashies",
        "dingo fucker",
        "dingo fuckers",
        "mil bag",
        "mil bags",
        "conspiracy theorist",
        "conspiracy theorists",
        "whore from Fife",
        "whore from Fifes",
        "boojie",
        "boojies",
        "book book",
        "book books",
        "cheese eating surrender monkey",
        "cheese eating surrender monkies",
        "idiot",
        "idiots",
        "jock",
        "jocks",
        "mack",
        "macks",
        "Merkin",
        "Merkins",
        "neche",
        "neches",
        "neejee",
        "neejees",
        "neechee",
        "neechees",
        "powderburn",
        "powderburns",
        "proddywhoddy",
        "proddywhoddies",
        "proddywoddy",
        "proddywoddies",
        "Rhine monkey",
        "Rhine monkies"
    ];
})(GraffitiExtension || (GraffitiExtension = {}));
var GraffitiExtension;
(function (GraffitiExtension) {
    GraffitiExtension.overlayContent = `
<div style="
background: linear-gradient(rgba(0,0,0,1), rgba(0,0,0,0));
border-radius: 8px;
padding: 15px 15px 50px;
text-align: center;
color: white;
font-size: 14px;
font-weight: normal;
">
<div style="margin: 0; padding: 0; font-size: 17px; font-weight:bold">This picture is protecting you from sensitive content, such as hate speech. Disable Qraffiti to view this content.</div>
<div style="margin: 5px 0 0 0; padding: 0">To learn more about cyberbullying, visit <a style="color: inherit; text-decoration: underline" href="http://www.endcyberbullying.org/">http://www.endcyberbullying.org/</a>.</div>
<div style="margin: 5px 0 0 0; padding: 0">To get support, visit <a style="color: inherit; text-decoration: underline" href="http://www.thetrevorproject.org/">http://www.thetrevorproject.org/</a>.</div>
</div>
`;
})(GraffitiExtension || (GraffitiExtension = {}));
/// <reference types="jquery" />
/// <reference types="chrome" />
/// <reference path="matchList.ts" />
/// <reference path="imageRetreiver.ts" />
/// <reference path="overlayContent.ts" />
var GraffitiExtension;
(function (GraffitiExtension) {
    class TextReplacer {
        constructor(rootNode) {
            this.rootNode = rootNode;
            this.isActive = true;
        }
        startReplacement() {
            return __awaiter(this, void 0, void 0, function* () {
                const tagsToMatch = "p,h1,h2,h3,h4,h5,h6";
                var promises = [];
                jQuery(this.rootNode)
                    .find(`${tagsToMatch}:not(${tagsToMatch} ${tagsToMatch})`)
                    .each((idx, child) => {
                    var $child = jQuery(child);
                    promises.push(this.handleText($child).then($new => {
                        return { old: $child, new: $new };
                    }));
                });
                var nodeMap = yield Promise.all(promises);
                // remove items that did not get replaced
                this.nodeMap = nodeMap.filter(pair => pair.new);
            });
        }
        toggleActiveStatus() {
            if (!this.nodeMap) {
                return; // nodes are not loaded yet, abort
            }
            this.isActive = !this.isActive;
            this.nodeMap.forEach(nodePair => {
                if (this.isActive) {
                    nodePair.old.replaceWith(nodePair.new);
                }
                else {
                    nodePair.new.replaceWith(nodePair.old);
                }
            });
        }
        handleText($node) {
            return __awaiter(this, void 0, void 0, function* () {
                if (this.isMatch($node.text())) {
                    return yield this.performReplacement($node);
                }
                return null;
            });
        }
        isMatch(text) {
            if (text.split(" ").length < 5) {
                // Only attempt match when at leat 5 words
                return false;
            }
            // get all lower case words without symbols and remove empty items
            text = text.toLowerCase().replace(/[^\w\s]/g, " ");
            var words = text.split(" ").filter(w => w);
            for (var i = 0; i < words.length; i++) {
                if (GraffitiExtension.matchPhrases.some(phrase => {
                    var phraseWords = phrase.split(" ");
                    if (phraseWords.length + i > words.length) {
                        // phrase is longer than remaining words in original text
                        return false;
                    }
                    // do all phrase words match this text word (+ peek next words)
                    return phraseWords.every((pWord, pidx) => words[i + pidx] == pWord);
                })) {
                    return true;
                }
            }
            return false;
        }
        performReplacement($node) {
            return __awaiter(this, void 0, void 0, function* () {
                var origHeight = $node.height();
                var origWidth = $node.width();
                var $newNode = jQuery("<div />")
                    .css({
                    minHeight: origHeight,
                    width: origWidth,
                    backgroundColor: "transparent",
                    display: $node.css("display"),
                    borderRadius: "8px"
                });
                $node.replaceWith($newNode);
                var imageDetails = yield new GraffitiExtension.ImageRetreiver().getRandomImage();
                $newNode.css({
                    background: `${imageDetails.primaryColor} url("${imageDetails.url}")`,
                    backgroundSize: "cover",
                    minHeight: origWidth / imageDetails.aspectRatio
                });
                $newNode.append(this.getOverlayContent);
                return $newNode;
            });
        }
        getOverlayContent() {
            return jQuery(GraffitiExtension.overlayContent);
        }
    }
    GraffitiExtension.TextReplacer = TextReplacer;
})(GraffitiExtension || (GraffitiExtension = {}));
/// <reference types="jquery" />
/// <reference types="chrome" />
/// <reference path="textReplacer.ts" />
var GraffitiExtension;
(function (GraffitiExtension) {
    class Bootstrapper {
        start() {
            return __awaiter(this, void 0, void 0, function* () {
                yield this.waitForDocumentReady();
                var replacer = new GraffitiExtension.TextReplacer(document.body);
                replacer.startReplacement();
                chrome.runtime.onMessage.addListener(msg => {
                    switch (msg.type) {
                        case "BROWSER_ACTION_ONCLICKED":
                            replacer.toggleActiveStatus();
                    }
                });
            });
        }
        waitForDocumentReady() {
            return __awaiter(this, void 0, void 0, function* () {
                var deferred = jQuery.Deferred();
                var loadingInterval = setInterval(() => {
                    if (/loaded|complete/.test(document.readyState)) {
                        clearInterval(loadingInterval);
                        deferred.resolve();
                    }
                }, 10);
                return deferred.promise;
            });
        }
    }
    new Bootstrapper().start();
})(GraffitiExtension || (GraffitiExtension = {}));
